%include '_verbs/arrange.sas';
%include '_verbs/drop.sas';
%include '_verbs/filter.sas';
%include '_verbs/join.sas';
%include '_verbs/keep.sas';
%include '_verbs/mutate.sas';
%include '_verbs/rename.sas';
%include '_verbs/select.sas';
%include '_verbs/summarize.sas';
